### PR TITLE
Create ilias_hu.lang

### PR DESCRIPTION
**Pull request by KissDaniGH**

### CODE REVIEW

**Comment by KissDaniGH** [comment]
Hi
could you please merge HUN files?
Thanks in advance, Daniel

**Comment by wanze** [comment]
Hi @KissDaniGH 
Thanks for the translations! It seems like the second commit 8b1375f got corrupted somehow. Would you like to commit these changes again before we merge?

Cheers Stefan

**Comment by KissDaniGH** [comment]
Hi Stefan 
ok, I close that and start a new one asap.
Daniel

**Comment by KissDaniGH** [comment]
here comes the #5 
regards, Daniel

**Pull request closed without merging**
